# Generated by Django 3.2.18 on 2023-05-05 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=58)),
                ('phone2', models.CharField(blank=True, max_length=58, null=True)),
                ('email', models.EmailField(max_length=100)),
                ('email2', models.EmailField(blank=True, max_length=100, null=True)),
                ('location', models.EmailField(max_length=100)),
                ('location2', models.EmailField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(choices=[('', 'Select Topic *'), ('OR', 'Order Inquiry'), ('PR', 'Product Inquiry'), ('OT', 'Other Inquiry')], max_length=2)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField(max_length=1000)),
                ('location', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Contact Us',
                'ordering': ['-date_created'],
            },
        ),
    ]
