# Generated by Django 3.2.18 on 2023-05-15 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='location',
        ),
    ]
