# Generated by Django 3.2.18 on 2023-05-17 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_remove_contact_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='location2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
